# Generated by Django 5.0.4 on 2024-04-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_registration_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_method',
        ),
    ]
